name: Pull request

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
